-- Initial catalog. Existing song IDs are preserved when rerun.
USE malayalam_heardle;

INSERT IGNORE INTO songs (id, title, movie, youtube_id) VALUES
(1, 'Entammede Jimikki Kammal', 'Velipadinte Pusthakam', 'IvkVJt4lhGA'),
(2, 'Malare', 'Premam', 'VmnXvn9AB7U'),
(3, 'Manikya Malaraya Poovi', 'Oru Adaar Love', 'W0fKl43QmIE'),
(4, 'Uyiril Thodum', 'Kumbalangi Nights', 'ZKhOs_Pc_7s'),
(5, 'Nenjodu Cherthu', 'Yuvvh', 'S5dMo6Jl3uU'),
(6, 'Onnam Ragam Paadi', 'Thoovanathumbikal', 'pBbHUxjiKd8'),
(7, 'Theythaka', 'Kudukku 2025', 'pzPu-6eC2Wg'),
(8, 'Padakali', 'Yodha', 'JDznrXqzDuI'),
(9, 'Aluva Puzhayude Theerathu', 'Premam', 'qHnd9Hls12w'),
(10, 'Karutha Penne', 'Thenmaavin Kombathu', 'hk9FOM-_1YA'),
(11, 'Pularikalo', 'Charlie', 'SmNJYC1Awug'),
(12, 'Illuminati', 'Aavesham', 'z8KjZyw4JYY'),
(14, 'Maaran', 'Kudukku 2025', '1kcrqTs7mO4'),
(15, 'Poove', 'Kudukku 2025', 'Gi9HSj2yyUE');

-- 250 additional songs.
INSERT INTO songs (title, movie, youtube_id) SELECT 'Thiruvaavaniraavu', 'Jacobinte Swargarajyam', 'VrrnflVEiMg' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'VrrnflVEiMg' OR LOWER(title) = LOWER('Thiruvaavaniraavu'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Oru Kari Mukilinu', 'Charlie', 'ArYW9uI-_LI' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'ArYW9uI-_LI' OR LOWER(title) = LOWER('Oru Kari Mukilinu'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Thaane Pookum', 'Sapthamashree Thaskaraha', 'HcxY6M8yj2c' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'HcxY6M8yj2c' OR LOWER(title) = LOWER('Thaane Pookum'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Ee Kaattu', 'Adam Joan', 'TFwZuS8Kkcc' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'TFwZuS8Kkcc' OR LOWER(title) = LOWER('Ee Kaattu'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Hemanthamen', 'Kohinoor', 'oxz5Xp1NSJk' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'oxz5Xp1NSJk' OR LOWER(title) = LOWER('Hemanthamen'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Thennal Nilavinte', 'Oru Muthassi Gadha', '0-QUOlYLp7U' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '0-QUOlYLp7U' OR LOWER(title) = LOWER('Thennal Nilavinte'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Chenthamara Chundil', 'Style', 'HCjwcYBu5iU' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'HCjwcYBu5iU' OR LOWER(title) = LOWER('Chenthamara Chundil'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Kamini', 'Anugraheethan Antony', 'FLz9hCjELWk' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'FLz9hCjELWk' OR LOWER(title) = LOWER('Kamini'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Uyire', 'Gauthamante Radham', '-hsdXiwA4c0' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '-hsdXiwA4c0' OR LOWER(title) = LOWER('Uyire'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Duppattawaali', 'Odum Kuthira Chaadum Kuthira', 'rwA4N8pj1XA' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'rwA4N8pj1XA' OR LOWER(title) = LOWER('Duppattawaali'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Mazhanila', 'Vikramadithyan', 'PM91C6Rpe1w' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'PM91C6Rpe1w' OR LOWER(title) = LOWER('Mazhanila'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Janah Meri Janah', 'Cappuccino', 'At9F0IifmBM' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'At9F0IifmBM' OR LOWER(title) = LOWER('Janah Meri Janah'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Aarum Kaanaathinnen', 'Oru Adaar Love', '3IzuahbwlnY' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '3IzuahbwlnY' OR LOWER(title) = LOWER('Aarum Kaanaathinnen'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Pokam Dhoore', 'Pokam Dhoore', 'tzk0IS3Q2zs' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'tzk0IS3Q2zs' OR LOWER(title) = LOWER('Pokam Dhoore'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Paavam Paavada', 'Paavada', 'v7sHWl1gc9I' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'v7sHWl1gc9I' OR LOWER(title) = LOWER('Paavam Paavada'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Lailakame', 'Ezra', 'FAn2i7gu32w' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'FAn2i7gu32w' OR LOWER(title) = LOWER('Lailakame'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Ithale Ponnithale', 'Am Ah', 'RnRCGdhBffM' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'RnRCGdhBffM' OR LOWER(title) = LOWER('Ithale Ponnithale'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Poomaram', 'Poomaram', 'xDbloPaf3s4' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'xDbloPaf3s4' OR LOWER(title) = LOWER('Poomaram'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Viral Thottaal Viriyunna', 'Phantom', 'idbbRBlKq1s' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'idbbRBlKq1s' OR LOWER(title) = LOWER('Viral Thottaal Viriyunna'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Katte Katte', 'Sathyam', '80-1wrorucM' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '80-1wrorucM' OR LOWER(title) = LOWER('Katte Katte'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Aararum Kaanathe', 'Chandrolsavam', 'a163uaLORI0' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'a163uaLORI0' OR LOWER(title) = LOWER('Aararum Kaanathe'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Kudajadriyil', 'Moham', 'lpEx3PwvSZ8' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'lpEx3PwvSZ8' OR LOWER(title) = LOWER('Kudajadriyil'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Idukki', 'Maheshinte Prathikaaram', 'NL5bYMXCSJ0' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'NL5bYMXCSJ0' OR LOWER(title) = LOWER('Idukki'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Sundariye Vaa', 'Chembakame', 'WRVPV5MkC8s' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'WRVPV5MkC8s' OR LOWER(title) = LOWER('Sundariye Vaa'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Chembakame', 'Chembakame', 'Wp2PI4q8EzI' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'Wp2PI4q8EzI' OR LOWER(title) = LOWER('Chembakame'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Marakkudayaal', 'Manasinakkare', 'eY7Q0hnru7Q' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'eY7Q0hnru7Q' OR LOWER(title) = LOWER('Marakkudayaal'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Muttathethum Thennale', 'Chandrolsavam', 'ZQYEDHY92bk' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'ZQYEDHY92bk' OR LOWER(title) = LOWER('Muttathethum Thennale'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Thottu Thottu', 'Diamond Necklace', 'FJ1QBAmuX-s' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'FJ1QBAmuX-s' OR LOWER(title) = LOWER('Thottu Thottu'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Vaanam Chaayum', 'Anarkali', 'hgWzBlC9Iso' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'hgWzBlC9Iso' OR LOWER(title) = LOWER('Vaanam Chaayum'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Ishtam Enikyishtam', 'Pranayam', 'QhCH4eeU8PI' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'QhCH4eeU8PI' OR LOWER(title) = LOWER('Ishtam Enikyishtam'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Manogatham Bhavan', 'Anuraga Karikkin Vellam', '2uTNC3V444o' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '2uTNC3V444o' OR LOWER(title) = LOWER('Manogatham Bhavan'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Pinakkamaano', 'Ananthabhadram', 'kg1Dj9cbZOk' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'kg1Dj9cbZOk' OR LOWER(title) = LOWER('Pinakkamaano'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Raavil Aaro', 'Soothradharan', '8oCeNqL7gvo' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '8oCeNqL7gvo' OR LOWER(title) = LOWER('Raavil Aaro'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Visile Visile', 'Sathyam', 'dqkY4Gfj-wY' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'dqkY4Gfj-wY' OR LOWER(title) = LOWER('Visile Visile'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Kayalondu Vattam Varache', 'Varayan', 'MvsPVlJX-10' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'MvsPVlJX-10' OR LOWER(title) = LOWER('Kayalondu Vattam Varache'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Akale', '9', 'FvDWCXN_dDs' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'FvDWCXN_dDs' OR LOWER(title) = LOWER('Akale'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Asalayavale', 'Khalifa', 'OsvCOcEspBI' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'OsvCOcEspBI' OR LOWER(title) = LOWER('Asalayavale'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Maanthrikam', 'Bethlehem Kudumba Unit', 'fSugljnCFFI' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'fSugljnCFFI' OR LOWER(title) = LOWER('Maanthrikam'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Kannadi Vaathil', 'London Bridge', '1wlSGxnutPA' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '1wlSGxnutPA' OR LOWER(title) = LOWER('Kannadi Vaathil'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Theru There', 'Role Models', 'Jjjx-8zFAq4' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'Jjjx-8zFAq4' OR LOWER(title) = LOWER('Theru There'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Periyavane', 'Khalifa', '_T_qoxPDTvc' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '_T_qoxPDTvc' OR LOWER(title) = LOWER('Periyavane'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Gold Rush', 'Khalifa', 'RmImj0u5CEA' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'RmImj0u5CEA' OR LOWER(title) = LOWER('Gold Rush'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Nenjinullil', 'Diamond Necklace', 'MgqvWshowNQ' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'MgqvWshowNQ' OR LOWER(title) = LOWER('Nenjinullil'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Minnalvala', 'Narivetta', 'izbydia9jz4' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'izbydia9jz4' OR LOWER(title) = LOWER('Minnalvala'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Kissayariyathe', 'Khalifa', 'JhcmlJ99J1g' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'JhcmlJ99J1g' OR LOWER(title) = LOWER('Kissayariyathe'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Kalapakkaara', 'King of Kotha', 'qZ9uZgDntNc' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'qZ9uZgDntNc' OR LOWER(title) = LOWER('Kalapakkaara'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Vennilavin Thaliralle', 'Neermathalam Poothakalam', '0w8RRqSEX6A' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '0w8RRqSEX6A' OR LOWER(title) = LOWER('Vennilavin Thaliralle'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Arikil Pathiye', 'Oru Murai Vanthu Paarthaya', 'VNg556FUOUs' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'VNg556FUOUs' OR LOWER(title) = LOWER('Arikil Pathiye'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Pamba Ganapathi', 'Pattalam', '75q1QV7aKjs' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '75q1QV7aKjs' OR LOWER(title) = LOWER('Pamba Ganapathi'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Kanmanipoove', 'Thudarum', 'RGg-Qx1rL9U' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'RGg-Qx1rL9U' OR LOWER(title) = LOWER('Kanmanipoove'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Venmathi', 'Hridayapoorvam', '_5WzsfTCz-E' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '_5WzsfTCz-E' OR LOWER(title) = LOWER('Venmathi'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Kannil Kashi Thumbakal', 'Dreams', '7ocAC2kDeho' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '7ocAC2kDeho' OR LOWER(title) = LOWER('Kannil Kashi Thumbakal'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Vaazhve Maayam', 'Bachelor Party D''EUX', 'nY-fbL50LsA' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'nY-fbL50LsA' OR LOWER(title) = LOWER('Vaazhve Maayam'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Vaisakha Sandhye', 'Nadodikkattu', 'GJCj4lfraDc' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'GJCj4lfraDc' OR LOWER(title) = LOWER('Vaisakha Sandhye'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Nadodi Poonthinkal', 'Ustaad', 'rCFLEKE_YmQ' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'rCFLEKE_YmQ' OR LOWER(title) = LOWER('Nadodi Poonthinkal'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Rojapoo Kavilathu', 'Chandamama', 'L7V3nDBKj4M' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'L7V3nDBKj4M' OR LOWER(title) = LOWER('Rojapoo Kavilathu'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Koottil Ninnum Mettil', 'Thalavattam', 'zHm3AX8knVU' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'zHm3AX8knVU' OR LOWER(title) = LOWER('Koottil Ninnum Mettil'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Raavil Poonthen', 'Naaduvaazhikal', 'o9gK2mKuEqs' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'o9gK2mKuEqs' OR LOWER(title) = LOWER('Raavil Poonthen'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Marannuvo Poomakale', 'Chakkaramuthu', 'Nrp-uSa0uZI' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'Nrp-uSa0uZI' OR LOWER(title) = LOWER('Marannuvo Poomakale'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Mandara Cheppundo', 'Dasharatham', 'FctVtK0Fp5c' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'FctVtK0Fp5c' OR LOWER(title) = LOWER('Mandara Cheppundo'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Pularoli', 'Bhaskar the Rascal', '7dLUzfLFq4s' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '7dLUzfLFq4s' OR LOWER(title) = LOWER('Pularoli'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Vellaram Kannulla Vellimoonga', 'Vellimoonga', 'GkrVVy2x7ec' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'GkrVVy2x7ec' OR LOWER(title) = LOWER('Vellaram Kannulla Vellimoonga'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Ullasa Gaayike', 'Adi Kapyare Koottamani', 'ehj1UpZJSrA' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'ehj1UpZJSrA' OR LOWER(title) = LOWER('Ullasa Gaayike'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Manassilayiram', 'Bhaskar the Rascal', 'vi20rbLlZrs' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'vi20rbLlZrs' OR LOWER(title) = LOWER('Manassilayiram'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Aattuthottil', 'Athiran', 'PcsvpfKPOMQ' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'PcsvpfKPOMQ' OR LOWER(title) = LOWER('Aattuthottil'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Oru Mozhi Parayam', 'Ira', 'pMGXW3sRuGk' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'pMGXW3sRuGk' OR LOWER(title) = LOWER('Oru Mozhi Parayam'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Omal Kanmani', 'Naran', 'HUv0sC4O1hk' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'HUv0sC4O1hk' OR LOWER(title) = LOWER('Omal Kanmani'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Sona Sona', 'Ben Johnson', 'cKyxTcwkvJc' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'cKyxTcwkvJc' OR LOWER(title) = LOWER('Sona Sona'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Mazhaneer Thullikal', 'Beautiful', 'OzvQFsYFkYo' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'OzvQFsYFkYo' OR LOWER(title) = LOWER('Mazhaneer Thullikal'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Vellarathaaram', 'Sarvam Maya', 'BVgNoVwsb6Y' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'BVgNoVwsb6Y' OR LOWER(title) = LOWER('Vellarathaaram'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Kanakkattu', 'Chiram', 'n_Z4rlE7M00' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'n_Z4rlE7M00' OR LOWER(title) = LOWER('Kanakkattu'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Chandare', 'Chiram', 'te9jOqxIDnI' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'te9jOqxIDnI' OR LOWER(title) = LOWER('Chandare'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Dingiri Dingale', 'Kurup', 'JqjXnOgygmU' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'JqjXnOgygmU' OR LOWER(title) = LOWER('Dingiri Dingale'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Thalatherichavar', 'Romancham', 'hvqnG6VjqV0' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'hvqnG6VjqV0' OR LOWER(title) = LOWER('Thalatherichavar'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Ashubha Mangalakaari', 'Super Sharanya', '81jbVOvOUTE' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '81jbVOvOUTE' OR LOWER(title) = LOWER('Ashubha Mangalakaari'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Mandarappoove', 'Kumari', 'yc0rN0pRIlA' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'yc0rN0pRIlA' OR LOWER(title) = LOWER('Mandarappoove'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Parudeesa', 'Bheeshma Parvam', 'O_ZIs4p14Fo' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'O_ZIs4p14Fo' OR LOWER(title) = LOWER('Parudeesa'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Maname', 'Aasha', 'qLT3u-v6iwg' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'qLT3u-v6iwg' OR LOWER(title) = LOWER('Maname'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Rani', 'Rani', 'IwcaPTnkpDU' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'IwcaPTnkpDU' OR LOWER(title) = LOWER('Rani'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Paathira Kaalam', 'Kurup', '-Q__mXqYo7Y' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '-Q__mXqYo7Y' OR LOWER(title) = LOWER('Paathira Kaalam'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Kaattuchembakam', 'Pallichattambi', 'kzpS-A3QJqE' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'kzpS-A3QJqE' OR LOWER(title) = LOWER('Kaattuchembakam'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Indraneelam Choodi', 'Varnakazhchakal', 'XQnFVhBbiKw' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'XQnFVhBbiKw' OR LOWER(title) = LOWER('Indraneelam Choodi'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'En Kanimalare', 'Philips and the Monkey Pen', 'wNkngDLREnY' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'wNkngDLREnY' OR LOWER(title) = LOWER('En Kanimalare'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Iniyenthunalkanam', 'Life Is Beautiful', 'FhUzAWavdTY' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'FhUzAWavdTY' OR LOWER(title) = LOWER('Iniyenthunalkanam'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Chembarathi Kammalittu', 'Manikyakkallu', 'sxNDkzZFuas' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'sxNDkzZFuas' OR LOWER(title) = LOWER('Chembarathi Kammalittu'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Oru Kathilola Njan', 'Vettam', 'Rz-hqTc1KXk' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'Rz-hqTc1KXk' OR LOWER(title) = LOWER('Oru Kathilola Njan'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Varthinkal Thellalle', 'Dreams', 'wxbi2fLT-gY' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'wxbi2fLT-gY' OR LOWER(title) = LOWER('Varthinkal Thellalle'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Mohikkum Neelmizhiyode', 'Manthrikam', 'xX00kcxNb60' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'xX00kcxNb60' OR LOWER(title) = LOWER('Mohikkum Neelmizhiyode'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Enthinu Veroru Sooryodayam', 'Mazhayethum Munpe', 'PCYXeJlyGAY' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'PCYXeJlyGAY' OR LOWER(title) = LOWER('Enthinu Veroru Sooryodayam'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Ariyathe Ariyathe', 'Ravanaprabhu', 'dikC8UmxxnE' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'dikC8UmxxnE' OR LOWER(title) = LOWER('Ariyathe Ariyathe'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Ezhazhakumay', 'Kakkakum Poochakum Kalyanam', 'ltKI9LyvZ1s' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'ltKI9LyvZ1s' OR LOWER(title) = LOWER('Ezhazhakumay'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Panineerumayi', 'Vishnu', 'Bug6L6wR8J8' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'Bug6L6wR8J8' OR LOWER(title) = LOWER('Panineerumayi'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Kanikkonnakal', 'Oru Abhibhashakante Case Diary', 'q9bZ_3NwNak' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'q9bZ_3NwNak' OR LOWER(title) = LOWER('Kanikkonnakal'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Vaathilppazuthilooden', 'Idanaazhiyil Oru Kaalocha', 'NRHolxcWBrI' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'NRHolxcWBrI' OR LOWER(title) = LOWER('Vaathilppazuthilooden'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Muthe Ninne', 'Amrutham', '7rjGU5amkpc' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '7rjGU5amkpc' OR LOWER(title) = LOWER('Muthe Ninne'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Aathmavin Pusthakathaalil', 'Mazhayethum Munpe', 'gvHH6FQ4LWs' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'gvHH6FQ4LWs' OR LOWER(title) = LOWER('Aathmavin Pusthakathaalil'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Innalakale', 'Honey Bee', 'XRQh7i5A8HM' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'XRQh7i5A8HM' OR LOWER(title) = LOWER('Innalakale'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Njan Kaanum Neram', 'Avatharam', 'LVtfVgYPrEo' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'LVtfVgYPrEo' OR LOWER(title) = LOWER('Njan Kaanum Neram'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Ramzan Nilavotha', 'Boy Friend', 'GxM0cF9lTuo' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'GxM0cF9lTuo' OR LOWER(title) = LOWER('Ramzan Nilavotha'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Mele Manathu', 'Chembakame', 'QjjMshasIQo' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'QjjMshasIQo' OR LOWER(title) = LOWER('Mele Manathu'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Aaro Padunnu Dhoore', 'Kadha Thudarunnu', '4dn47zj7ih4' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '4dn47zj7ih4' OR LOWER(title) = LOWER('Aaro Padunnu Dhoore'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Mele Vellithinkal', 'Thanmatra', 'MAueQXTHyqw' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'MAueQXTHyqw' OR LOWER(title) = LOWER('Mele Vellithinkal'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Drona Theme', 'Drona', 'k2XcG4g8xxI' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'k2XcG4g8xxI' OR LOWER(title) = LOWER('Drona Theme'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Neeyam Thanalinu', 'Cocktail', '61I8mDlMP2U' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '61I8mDlMP2U' OR LOWER(title) = LOWER('Neeyam Thanalinu'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Perilla Rajyathe', 'Bodyguard', 'AdNRVLfcJkQ' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'AdNRVLfcJkQ' OR LOWER(title) = LOWER('Perilla Rajyathe'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Mazhathullikal', 'Vettam', 'brivDcJamGY' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'brivDcJamGY' OR LOWER(title) = LOWER('Mazhathullikal'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Anuraaga Vilochananayi', 'Neelathaamara', 'fFU5OxdXf70' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'fFU5OxdXf70' OR LOWER(title) = LOWER('Anuraaga Vilochananayi'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Anchikonchathedee', 'Drona', 'hcpJTyNO8uY' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'hcpJTyNO8uY' OR LOWER(title) = LOWER('Anchikonchathedee'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Kizhakku Pookkum', 'Anwar', 'YrLRhuim5aM' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'YrLRhuim5aM' OR LOWER(title) = LOWER('Kizhakku Pookkum'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Lajjavathiye', '4 The People', 'sKc9dOcbdV4' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'sKc9dOcbdV4' OR LOWER(title) = LOWER('Lajjavathiye'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Venmegham', '2018', 'LVbbzfQ9dac' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'LVbbzfQ9dac' OR LOWER(title) = LOWER('Venmegham'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Ore Nila Ore Veyil', 'BTech', '5VV8WqVecqQ' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '5VV8WqVecqQ' OR LOWER(title) = LOWER('Ore Nila Ore Veyil'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Minnal Minnane', '2018', 'Qn8uH_BkFiI' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'Qn8uH_BkFiI' OR LOWER(title) = LOWER('Minnal Minnane'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Uyirayi Maarave', '2018', 'jOJFRtFuV7c' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'jOJFRtFuV7c' OR LOWER(title) = LOWER('Uyirayi Maarave'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Pavizha Mazha', 'Athiran', 'P-jKtzUuVcM' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'P-jKtzUuVcM' OR LOWER(title) = LOWER('Pavizha Mazha'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Neela Shalabhame', 'Charminar', '-1T7jTnpDqw' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '-1T7jTnpDqw' OR LOWER(title) = LOWER('Neela Shalabhame'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Thararaathara Moolana', 'Shikkari Shambhu', 'LpS7hBp992U' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'LpS7hBp992U' OR LOWER(title) = LOWER('Thararaathara Moolana'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Innithile', '2018', '7i_asZ8YlDY' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '7i_asZ8YlDY' OR LOWER(title) = LOWER('Innithile'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Mulla Poovithalo', 'Abrahaminte Santhathikal', 'eECs3R6fr-s' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'eECs3R6fr-s' OR LOWER(title) = LOWER('Mulla Poovithalo'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Pulkodiyil Thoomani', 'Take Off', 'B2DGTD1Heg4' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'B2DGTD1Heg4' OR LOWER(title) = LOWER('Pulkodiyil Thoomani'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Veluveluthoru', 'Two Countries', 'Ies3Ea2dwMQ' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'Ies3Ea2dwMQ' OR LOWER(title) = LOWER('Veluveluthoru'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Vijanatheerame', 'Theevandi', 'XlCvewtwe2A' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'XlCvewtwe2A' OR LOWER(title) = LOWER('Vijanatheerame'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Jeevamshamayi', 'Theevandi', 'DInfmi-YIiw' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'DInfmi-YIiw' OR LOWER(title) = LOWER('Jeevamshamayi'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Ee Khalbitha', 'IDI', 'T4K6CGPiyF4' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'T4K6CGPiyF4' OR LOWER(title) = LOWER('Ee Khalbitha'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Ummarathe Chembakathe', 'Ivan Maryadaraman', 'eGXe80xfVYg' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'eGXe80xfVYg' OR LOWER(title) = LOWER('Ummarathe Chembakathe'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Vasanthamallike', 'Chandrettan Evideya', 'OdsVnaB5uHc' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'OdsVnaB5uHc' OR LOWER(title) = LOWER('Vasanthamallike'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Vaathil Melle', 'Neram', 'r3fhuJJRcYc' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'r3fhuJJRcYc' OR LOWER(title) = LOWER('Vaathil Melle'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Enthanu Khalbe', 'KL10 Pathu', '9gmq8hh3tYM' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '9gmq8hh3tYM' OR LOWER(title) = LOWER('Enthanu Khalbe'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Thanne Thanne', 'Two Countries', 'LnH9djDHEOI' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'LnH9djDHEOI' OR LOWER(title) = LOWER('Thanne Thanne'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Chenthengin Chaarathu', 'Two Countries', 'gCqLE1KOPPs' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'gCqLE1KOPPs' OR LOWER(title) = LOWER('Chenthengin Chaarathu'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Varnajaalam', 'Bethlehem Kudumba Unit', 'xy9z0d9uHcA' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'xy9z0d9uHcA' OR LOWER(title) = LOWER('Varnajaalam'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Mazhamukhile', 'Saaradhi', 'yQLif3827pQ' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'yQLif3827pQ' OR LOWER(title) = LOWER('Mazhamukhile'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Ilakozhiye', 'Thalavara', 's7fpixCzxBc' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 's7fpixCzxBc' OR LOWER(title) = LOWER('Ilakozhiye'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Manamariyunnolu', 'Porinju Mariyam Jose', 'I6eQUn_78Ck' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'I6eQUn_78Ck' OR LOWER(title) = LOWER('Manamariyunnolu'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Neela Nilave', 'RDX', 'nYEoxne_20Y' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'nYEoxne_20Y' OR LOWER(title) = LOWER('Neela Nilave'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Aaradhike', 'Ambili', 'dAezp422I_A' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'dAezp422I_A' OR LOWER(title) = LOWER('Aaradhike'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Elamalakaadinullil', 'Pathaam Valavu', 'KgCUwwIj5f8' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'KgCUwwIj5f8' OR LOWER(title) = LOWER('Elamalakaadinullil'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Kiliye', 'ARM', 'B2UBMTA57JI' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'B2UBMTA57JI' OR LOWER(title) = LOWER('Kiliye'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Parayuvaan', 'Ishq', 'IWOPRFRNj3g' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'IWOPRFRNj3g' OR LOWER(title) = LOWER('Parayuvaan'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Chirimanimulle', 'Lion', 'Qsyzi89H9jA' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'Qsyzi89H9jA' OR LOWER(title) = LOWER('Chirimanimulle'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Olu', 'Maniyarayile Ashokan', 'RvpdHH_agAU' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'RvpdHH_agAU' OR LOWER(title) = LOWER('Olu'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Ranam Title Track', 'Ranam', 'UImrau29cu8' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'UImrau29cu8' OR LOWER(title) = LOWER('Ranam Title Track'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Mazha', 'Shikkari Shambhu', 'oargaN_6gdA' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'oargaN_6gdA' OR LOWER(title) = LOWER('Mazha'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Neeyilla Neram', 'Luca', 'bY_LdUERXjQ' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'bY_LdUERXjQ' OR LOWER(title) = LOWER('Neeyilla Neram'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Nee Himamazhayayi', 'Edakkad Battalion 06', 'nKEVIuya2kY' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'nKEVIuya2kY' OR LOWER(title) = LOWER('Nee Himamazhayayi'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Iniyum Kaanan Varam', 'Adios Amigo', 'SH6t6okGOco' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'SH6t6okGOco' OR LOWER(title) = LOWER('Iniyum Kaanan Varam'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Delulu Delulu', 'Athi Bheekara Kaamukan', 'yE3Ymg8DcyM' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'yE3Ymg8DcyM' OR LOWER(title) = LOWER('Delulu Delulu'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Pacha Parishkari', 'Pacha Parishkari', 'tz6Gy-X65K0' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'tz6Gy-X65K0' OR LOWER(title) = LOWER('Pacha Parishkari'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Manne Nambi', 'Adios Amigo', '6JckvJdP1Yw' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '6JckvJdP1Yw' OR LOWER(title) = LOWER('Manne Nambi'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Mathara', 'Khalifa', 'rVYbguORmT4' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'rVYbguORmT4' OR LOWER(title) = LOWER('Mathara'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Aayiram Aura', 'Aayiram Aura', 'Qd85V7IMS8M' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'Qd85V7IMS8M' OR LOWER(title) = LOWER('Aayiram Aura'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Chiri Thottu', 'Sarvam Maya', 'D76XBkNoeac' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'D76XBkNoeac' OR LOWER(title) = LOWER('Chiri Thottu'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Anthiveyil Ponnuthirum', 'Ulladakkam', 'G3UefvEW6JU' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'G3UefvEW6JU' OR LOWER(title) = LOWER('Anthiveyil Ponnuthirum'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Jaalakaari', 'Balti', 'w_XSgUCn_v0' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'w_XSgUCn_v0' OR LOWER(title) = LOWER('Jaalakaari'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Heart Attack', 'Painkili', 'avlXrTRrHaM' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'avlXrTRrHaM' OR LOWER(title) = LOWER('Heart Attack'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Moovanthi Thazhvarayil', 'Kanmadam', 'p74fSxKEmjo' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'p74fSxKEmjo' OR LOWER(title) = LOWER('Moovanthi Thazhvarayil'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Moovanthiyaayi', 'Pakshe', 'a2vksPh6IRA' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'a2vksPh6IRA' OR LOWER(title) = LOWER('Moovanthiyaayi'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Neeraaduvaan Nilayil', 'Nakhakshathangal', 'pfOJPZHz228' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'pfOJPZHz228' OR LOWER(title) = LOWER('Neeraaduvaan Nilayil'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Sreelavasantham', 'Nandanam', 'ZYvd85PoXQc' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'ZYvd85PoXQc' OR LOWER(title) = LOWER('Sreelavasantham'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Maanmizhi Poovu', 'Mahasamudram', 'lPqJEA3wR-s' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'lPqJEA3wR-s' OR LOWER(title) = LOWER('Maanmizhi Poovu'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Pinneyum Pinneyum', 'Krishnagudiyil Oru Pranayakaalathu', 'NCcZ6TC9ANo' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'NCcZ6TC9ANo' OR LOWER(title) = LOWER('Pinneyum Pinneyum'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Sundarano Sooriyano', 'Kanaka Simhasanam', 'oUbqUK4sH-8' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'oUbqUK4sH-8' OR LOWER(title) = LOWER('Sundarano Sooriyano'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Sooryamshu Oro Vayalpoovilum', 'Pakshe', 'VqeqEPj_nOw' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'VqeqEPj_nOw' OR LOWER(title) = LOWER('Sooryamshu Oro Vayalpoovilum'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Kuyil Paattil Oonjal', 'Aparichithan', 'ycFsFUTBhOY' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'ycFsFUTBhOY' OR LOWER(title) = LOWER('Kuyil Paattil Oonjal'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Muthuchippy Chellakkanna', 'Chemistry', '_TWojmgEWGs' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '_TWojmgEWGs' OR LOWER(title) = LOWER('Muthuchippy Chellakkanna'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Karimizhiyaale Oru Kadha', 'Snehithan', 'ZpYx87VILPA' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'ZpYx87VILPA' OR LOWER(title) = LOWER('Karimizhiyaale Oru Kadha'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Bhasuri', 'Rathrimazha', 's8YvKgf0EW0' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 's8YvKgf0EW0' OR LOWER(title) = LOWER('Bhasuri'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Muthe Muthe', 'Kana Kanmani', 'bh7r3Kr_WhA' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'bh7r3Kr_WhA' OR LOWER(title) = LOWER('Muthe Muthe'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Pular Manjupole', 'En Jeevane', '0DqFR1EeLnw' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '0DqFR1EeLnw' OR LOWER(title) = LOWER('Pular Manjupole'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Aaroraal Pularmazhayil', 'Pattalam', 'l_F4vl5Szwg' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'l_F4vl5Szwg' OR LOWER(title) = LOWER('Aaroraal Pularmazhayil'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Gandharajan Poovidarnnu', 'Calendar', 'K4bN6ipMAoU' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'K4bN6ipMAoU' OR LOWER(title) = LOWER('Gandharajan Poovidarnnu'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Karineela Kannilenthedi', 'Chakkaramuthu', 'wtB2IdJcbzg' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'wtB2IdJcbzg' OR LOWER(title) = LOWER('Karineela Kannilenthedi'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Kudamullakkadavil', 'Vellithira', 'tcX_101zP8M' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'tcX_101zP8M' OR LOWER(title) = LOWER('Kudamullakkadavil'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Kaatil Ila', 'Udaharanam Sujatha', 'VEUj5FVTFcU' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'VEUj5FVTFcU' OR LOWER(title) = LOWER('Kaatil Ila'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Junile Nilamazhayil', 'Nammal Thammil', 'th7EuCe6QEk' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'th7EuCe6QEk' OR LOWER(title) = LOWER('Junile Nilamazhayil'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Chakkarakkili', 'Vellinakshatram', 'PaUF5ldSfco' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'PaUF5ldSfco' OR LOWER(title) = LOWER('Chakkarakkili'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Varamanjalaadiya', 'Pranayavarnangal', 'JeZC81maYNI' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'JeZC81maYNI' OR LOWER(title) = LOWER('Varamanjalaadiya'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Oru Pattin Kattil', 'Dubai', '6Ea2Nsp6vaU' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '6Ea2Nsp6vaU' OR LOWER(title) = LOWER('Oru Pattin Kattil'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Sarike Ninne Kanan', 'Raakilipattu', '1ci219EAqJA' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '1ci219EAqJA' OR LOWER(title) = LOWER('Sarike Ninne Kanan'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Thanka Thinkal', 'Indraprastham', '-xC1EgO-Yew' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '-xC1EgO-Yew' OR LOWER(title) = LOWER('Thanka Thinkal'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Ethrayo Janmamayi', 'Summer in Bethlehem', 'ZRLcpR3jl9o' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'ZRLcpR3jl9o' OR LOWER(title) = LOWER('Ethrayo Janmamayi'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Onnamkili Ponnankili', 'Kilichundan Mambazham', 'o858vJHqKMo' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'o858vJHqKMo' OR LOWER(title) = LOWER('Onnamkili Ponnankili'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Ee Thanutha', 'Anarkali', 'nYgN4nWQ9a8' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'nYgN4nWQ9a8' OR LOWER(title) = LOWER('Ee Thanutha'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Chanthu Kudanjoru', 'Chanthupottu', 'Ak9mgK7FP5k' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'Ak9mgK7FP5k' OR LOWER(title) = LOWER('Chanthu Kudanjoru'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Thakilu Pukilu', 'Ravanaprabhu', 'eJNM9_wRvuc' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'eJNM9_wRvuc' OR LOWER(title) = LOWER('Thakilu Pukilu'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Pazhanimala', 'Narasimham', 'ydggK52urz8' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'ydggK52urz8' OR LOWER(title) = LOWER('Pazhanimala'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Chinnamma Adi', 'Oppam', '97L9VAGj4Jc' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '97L9VAGj4Jc' OR LOWER(title) = LOWER('Chinnamma Adi'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Chandanamani', 'Praja', '_hgXOyA97dI' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '_hgXOyA97dI' OR LOWER(title) = LOWER('Chandanamani'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Akaleyo Nee Akaleyo', 'Grandmaster', '15D4SVCVsxQ' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '15D4SVCVsxQ' OR LOWER(title) = LOWER('Akaleyo Nee Akaleyo'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Oru Dinam', 'Big Brother', 'WvwAx3ebEwc' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'WvwAx3ebEwc' OR LOWER(title) = LOWER('Oru Dinam'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Kaanana Kuyile', 'Mr. Brahmachari', '7mEaf8KMRZk' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '7mEaf8KMRZk' OR LOWER(title) = LOWER('Kaanana Kuyile'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'May Masam', 'Natturajavu', 'WJYhdl7K5Yc' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'WJYhdl7K5Yc' OR LOWER(title) = LOWER('May Masam'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Vinnile Gandharva', 'Rajavinte Makan', 'IoteCSukN4E' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'IoteCSukN4E' OR LOWER(title) = LOWER('Vinnile Gandharva'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Okkela Okkela', 'Varnapakittu', 'bOrgCQrSxpU' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'bOrgCQrSxpU' OR LOWER(title) = LOWER('Okkela Okkela'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Chellathamare', 'Hallo', 'nc__b-NIglU' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'nc__b-NIglU' OR LOWER(title) = LOWER('Chellathamare'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Aarattu Kadavinkal', 'Venkalam', '8WjFTs4xNcc' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '8WjFTs4xNcc' OR LOWER(title) = LOWER('Aarattu Kadavinkal'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Pulare Poonkodiyil', 'Amaram', 'z1uCrvgXW-M' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'z1uCrvgXW-M' OR LOWER(title) = LOWER('Pulare Poonkodiyil'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Olikkunnuvo', 'Champakulam Thachan', 'x-ocUzxywH0' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'x-ocUzxywH0' OR LOWER(title) = LOWER('Olikkunnuvo'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Pramadhavanam', 'His Highness Abdullah', 'ZRdHUj7gVSc' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'ZRdHUj7gVSc' OR LOWER(title) = LOWER('Pramadhavanam'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Rajeevam Vidarum Nin Mizhikal', 'Belt Mathai', 'ASsjUNF1Pgc' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'ASsjUNF1Pgc' OR LOWER(title) = LOWER('Rajeevam Vidarum Nin Mizhikal'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Sreeraagamo', 'Pavithram', 'aD9lDmwt9rk' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'aD9lDmwt9rk' OR LOWER(title) = LOWER('Sreeraagamo'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Tharake Mizhiyithalil', 'Choola', 'tSlDr-FpX_M' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'tSlDr-FpX_M' OR LOWER(title) = LOWER('Tharake Mizhiyithalil'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Harimuraleeravam', 'Aaraam Thampuran', '94tDeXtnHYA' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '94tDeXtnHYA' OR LOWER(title) = LOWER('Harimuraleeravam'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Thamburu Kulir Choodiyo', 'Soorya Gayathri', 'RSHZ2yOuL-c' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'RSHZ2yOuL-c' OR LOWER(title) = LOWER('Thamburu Kulir Choodiyo'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Mayamayooram', 'Vadakkunokkiyanthram', '24gfxvQCuf0' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '24gfxvQCuf0' OR LOWER(title) = LOWER('Mayamayooram'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Raathinkal Poothaali', 'Ee Puzhayum Kadannu', 'QRQ0SQ9zmdA' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'QRQ0SQ9zmdA' OR LOWER(title) = LOWER('Raathinkal Poothaali'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Iniyum Mizhikal Nirayaruthe', 'Ben Johnson', 'ty9PqxXHmKU' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'ty9PqxXHmKU' OR LOWER(title) = LOWER('Iniyum Mizhikal Nirayaruthe'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Thoomanjin Nenjilothungi', 'Samooham', '0UHJgumPFvI' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '0UHJgumPFvI' OR LOWER(title) = LOWER('Thoomanjin Nenjilothungi'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Kannadi Kayyil', 'Pavam Pavam Rajakumaran', 'zc8tAFoM5NA' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'zc8tAFoM5NA' OR LOWER(title) = LOWER('Kannadi Kayyil'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Mounathin Idanazhiyil', 'Malootty', 'yaTYx9dQP18' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'yaTYx9dQP18' OR LOWER(title) = LOWER('Mounathin Idanazhiyil'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Paathira Pullunarnnu', 'Ee Puzhayum Kadannu', 'YDj3bN4eer4' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'YDj3bN4eer4' OR LOWER(title) = LOWER('Paathira Pullunarnnu'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Oru Vaakku Mindathe', 'July 4', 'Ki1HjR9VuGw' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'Ki1HjR9VuGw' OR LOWER(title) = LOWER('Oru Vaakku Mindathe'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Nalambalam Anayaan', 'Sringaravelan', 'umkLWIs90p8' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'umkLWIs90p8' OR LOWER(title) = LOWER('Nalambalam Anayaan'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Mundiri Paadam', 'Kochi Rajavu', 'siprAVDdSgg' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'siprAVDdSgg' OR LOWER(title) = LOWER('Mundiri Paadam'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Ente Ellam Ellam Alle', 'Meesamadhavan', 'sZvDWK8bjt8' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'sZvDWK8bjt8' OR LOWER(title) = LOWER('Ente Ellam Ellam Alle'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Karimizhi Kuruviye', 'Meesamadhavan', 'hraTNj9Au-A' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'hraTNj9Au-A' OR LOWER(title) = LOWER('Karimizhi Kuruviye'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Margazhiye Mallikaye', 'Megham', 'hBT1gbs6xpg' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'hBT1gbs6xpg' OR LOWER(title) = LOWER('Margazhiye Mallikaye'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Omal Chiriyo', 'Georgettans Pooram', 'Ef7lWtjDL7g' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'Ef7lWtjDL7g' OR LOWER(title) = LOWER('Omal Chiriyo'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Kanne Kanne', 'Shylock', 'vOMV5tlslPs' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'vOMV5tlslPs' OR LOWER(title) = LOWER('Kanne Kanne'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Poomaname', 'Abraham Ozler', 'oOuQAPIGG_g' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'oOuQAPIGG_g' OR LOWER(title) = LOWER('Poomaname'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Yarusalem Naayaka', 'Abrahaminte Santhathikal', 'hL41UM8_54E' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'hL41UM8_54E' OR LOWER(title) = LOWER('Yarusalem Naayaka'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Thekkan Katte', 'Ezhupunna Tharakan', 'QdKTT6rv3Jc' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'QdKTT6rv3Jc' OR LOWER(title) = LOWER('Thekkan Katte'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Rathipushpam', 'Bheeshma Parvam', 'R9HJsEv6_1g' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'R9HJsEv6_1g' OR LOWER(title) = LOWER('Rathipushpam'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Chenthaamaraye Vaa', 'Thaskaraveeran', 'jWj1OCeztf0' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'jWj1OCeztf0' OR LOWER(title) = LOWER('Chenthaamaraye Vaa'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Mazhaye Mazhaye', 'James and Alice', 'zp-zzAu4uCw' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'zp-zzAu4uCw' OR LOWER(title) = LOWER('Mazhaye Mazhaye'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Eden Thottam', 'Adam Joan', '1HPL0aQNPsU' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '1HPL0aQNPsU' OR LOWER(title) = LOWER('Eden Thottam'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Makale Paathi Malare', 'Champakulam Thachan', 'f9ItjdKemAY' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'f9ItjdKemAY' OR LOWER(title) = LOWER('Makale Paathi Malare'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Vikaara Naukayumayi', 'Amaram', 'qboVkft8TtI' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'qboVkft8TtI' OR LOWER(title) = LOWER('Vikaara Naukayumayi'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Omane Thankame', 'Mizhi Randilum', 'NNecJkGcr9o' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'NNecJkGcr9o' OR LOWER(title) = LOWER('Omane Thankame'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Samshayam', 'Samshayam', 'qt2sqSmgCxo' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'qt2sqSmgCxo' OR LOWER(title) = LOWER('Samshayam'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Kunnimani Cheppu', 'Ponmuttayidunna Thaaravu', 'OrtQgvPzw3w' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'OrtQgvPzw3w' OR LOWER(title) = LOWER('Kunnimani Cheppu'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Chingamasam Vannu Chernnal', 'Meesamadhavan', 'IL5byzq70ls' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'IL5byzq70ls' OR LOWER(title) = LOWER('Chingamasam Vannu Chernnal'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Oru Kinnaragaanam', 'Speed Track', '5Xkhg1zxh-4' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '5Xkhg1zxh-4' OR LOWER(title) = LOWER('Oru Kinnaragaanam'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Nenjileri Theeye', 'Ramaleela', 'DSv00cI_UG4' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'DSv00cI_UG4' OR LOWER(title) = LOWER('Nenjileri Theeye'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Njano Ravo', 'Kammara Sambhavam', 'NkmsdwnTF50' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'NkmsdwnTF50' OR LOWER(title) = LOWER('Njano Ravo'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Janamanassin', 'One', 'Ive4V17F3rg' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'Ive4V17F3rg' OR LOWER(title) = LOWER('Janamanassin'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Kettille Kettille', 'Pokkiri Raja', 'igbJVbo9vNY' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'igbJVbo9vNY' OR LOWER(title) = LOWER('Kettille Kettille'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'I Love You Mummy', 'Bhaskar the Rascal', '5alVZs9UfhY' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '5alVZs9UfhY' OR LOWER(title) = LOWER('I Love You Mummy'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Niranaazhi Ponnil', 'Valyettan', 'a_0D0RbzGv8' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'a_0D0RbzGv8' OR LOWER(title) = LOWER('Niranaazhi Ponnil'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Pala Palli Thiruppalli', 'Kaduva', 'ZLtrPJgEHp4' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'ZLtrPJgEHp4' OR LOWER(title) = LOWER('Pala Palli Thiruppalli'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Mizhiyil Mizhiyil', 'Maayabazar', '0NMaBMWIvPg' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '0NMaBMWIvPg' OR LOWER(title) = LOWER('Mizhiyil Mizhiyil'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Parayathe Vannen', 'Bro Daddy', 'ODFwbAeMsHs' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'ODFwbAeMsHs' OR LOWER(title) = LOWER('Parayathe Vannen'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Kanninima Neele', 'Anwar', '_hNflcJc0Bc' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '_hNflcJc0Bc' OR LOWER(title) = LOWER('Kanninima Neele'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Kaana Kuyile', 'Bro Daddy', '5t1qXRdVDqM' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = '5t1qXRdVDqM' OR LOWER(title) = LOWER('Kaana Kuyile'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Aavani Ponnunjal', 'Kottaram Veetile Apputtan', 'cVIpeRvNr_A' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'cVIpeRvNr_A' OR LOWER(title) = LOWER('Aavani Ponnunjal'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Thalikku Ponnu', 'Daivathinte Makan', 'o82t3SnqG0U' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'o82t3SnqG0U' OR LOWER(title) = LOWER('Thalikku Ponnu'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Kodamanjin Thaazhvarayil', 'Kochu Kochu Santhoshangal', 'u_mf5oGCci4' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'u_mf5oGCci4' OR LOWER(title) = LOWER('Kodamanjin Thaazhvarayil'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Manjil Kulikkum', 'Veruthe Oru Bharya', 'Lpr-4JxnCis' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'Lpr-4JxnCis' OR LOWER(title) = LOWER('Manjil Kulikkum'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Maattupetti Koyilile', 'Mayilattam', 'u8y_BEx-ffA' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'u8y_BEx-ffA' OR LOWER(title) = LOWER('Maattupetti Koyilile'));
INSERT INTO songs (title, movie, youtube_id) SELECT 'Melleyonnu Paadi', 'Manasinakkare', 'VK5mUPx9iNM' WHERE NOT EXISTS (SELECT 1 FROM songs WHERE youtube_id = 'VK5mUPx9iNM' OR LOWER(title) = LOWER('Melleyonnu Paadi'));

-- Short dialogue clues; aliases accept common English spellings and Malayalam titles.
INSERT IGNORE INTO dialogues (dialogue, movie, aliases, source_url) VALUES
('Nee po mone Dinesha!', 'Narasimham', JSON_ARRAY('Narasimham', 'നരസിംഹം'), 'https://www.cinemaexpress.com/malayalam/news/2026/Mar/12/mohanlal-philosophises-po-mone-dinesha-line-from-narasimham'),
('Shammi hero aada, hero!', 'Kumbalangi Nights', JSON_ARRAY('Kumbalangi Nights', 'Kumbalangi Night', 'കുമ്പളങ്ങി നൈറ്റ്സ്'), 'https://www.thenewsminute.com/article/shammi-hero-da-hero-mohammed-shami-uses-kumbalangi-nights-dialogue-viral-video-117211'),
('Polandine patti oraksharam mindaruthu!', 'Sandesham', JSON_ARRAY('Sandesham', 'Sandhesham', 'സന്ദേശം'), 'https://www.reddit.com/r/MalayalamMovies/comments/ting1a/'),
('Lelu allu, lelu allu!', 'Thenmavin Kombath', JSON_ARRAY('Thenmavin Kombath', 'Thenmavin Kombathu', 'Thenmaavin Kombathu', 'Thenmaavin Kombath', 'തേന്മാവിൻ കൊമ്പത്ത്'), 'https://www.reddit.com/r/Kerala/comments/xc85gr/');

-- Five clues per film, ordered from broad to specific.
INSERT IGNORE INTO movie_puzzles (movie, aliases, clues) VALUES
('Drishyam', JSON_ARRAY('Drishyam', 'ദൃശ്യം'), JSON_ARRAY('A family faces a crisis that threatens its ordinary life.', 'The story takes place in a village in Kerala.', 'The father runs a cable television business and loves movies.', 'A disappearance leads to a police investigation into Georgekutty and his family.', 'Mohanlal plays Georgekutty in this 2013 thriller directed by Jeethu Joseph.')),
('Manichitrathazhu', JSON_ARRAY('Manichitrathazhu', 'Manichithrathazhu', 'മണിച്ചിത്രത്താഴ്'), JSON_ARRAY('A family home becomes the setting for mysterious events.', 'An old legend about a dancer hangs over the household.', 'A couple named Ganga and Nakulan move into the ancestral house.', 'Dr. Sunny investigates Ganga’s connection to Nagavalli.', 'Shobana, Mohanlal and Suresh Gopi star in this 1993 psychological thriller directed by Fazil.')),
('Minnal Murali', JSON_ARRAY('Minnal Murali', 'മിന്നൽ മുരളി'), JSON_ARRAY('Two ordinary people discover extraordinary abilities.', 'The story is set in the fictional village of Kurukkanmoola.', 'A lightning strike changes the lives of both men.', 'Jaison is a tailor, while Shibu works at a tea shop.', 'Tovino Thomas plays the superhero in this 2021 film directed by Basil Joseph.'));
